{% set name = "blasr" %}
{% set version = "5.3.5" %}
{% set sha256 = "006822e6964d9947c76d1b76430e1192ecb47941eef2ba49ebf137875e539d7d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/BioinformaticsArchive/{{ name }}/archive/refs/heads/master.zip
  sha256: {{ sha256 }}

about:
  home: https://github.com/BioinformaticsArchive/blasr
  license: BSD-3-Clause-Clear
  summary: BLASR - The PacBio long read aligner

extra:
  recipe-maintainers:
    - pb-dseifert
  skip-lints:
    #repackaged binary
    - should_be_noarch_generic

build:
  number: 2
  run_exports:
    - {{ pin_subpackage("blasr", max_pin="x.x.x") }}  
  skip: True  # [osx]

requirements:
  build:
    - gcc_linux-aarch64
    - gxx_linux-aarch64
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    
test:
  commands:
    - blasr -h
