package:
  name: mugsy
  version: 1.2.3

source:
  {% if target_platform == "linux-aarch64" %}
  url: https://github.com/kloetzl/mugsy/archive/refs/heads/master.zip
  md5: 0dc56fedaec9117fcab576f6ba4365e6
  {% else %}
  url: http://downloads.sourceforge.net/project/mugsy/mugsy_x86-64-v1r2.3.tgz
  md5: c4208cce45ff76f3fc7643764453617b
  {% endif %}
  patches:
    - perl-env.patch

build:
  noarch: generic
  number: 6
  run_exports:
    - {{ pin_subpackage('mugsy', max_pin="x") }}

requirements:
  run:
    - perl
    - sed

about:
  home: http://mugsy.sourceforge.net
  license: Artistic License 2.0
  summary: Mugsy is a multiple whole genome aligner.
  license_file: LICENSE
